In [1]:
# Dependency needed to install file 

%pip install xlrd openpyxl

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
     ---------------------------------------- 96.6/96.6 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: openpyxl in c:\users\yaram\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: et_xmlfile in c:\users\yaram\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import required library

import pandas as pd

In [17]:
import pandas as pd

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"
df = pd.read_csv(url)
##df = pd.read_csv("Product_sales.csv")##local

In [19]:
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [20]:
xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n9LOuKI9SlUa1b5zkaCMeg/Product-sales.xlsx'
df = pd.read_excel(xlsx_path)
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [21]:
x = df[['Quantity']]
x

   Quantity
0         2
1         3
2         5
3        10
4         1

In [22]:
# Get the column as a series

x = df['Product']
x

0        Laptop
1    Smartphone
2    Desk Chair
3      Notebook
4       Monitor
Name: Product, dtype: object

In [23]:
# Get the column as a dataframe

x = df[['Quantity']]
type(x)

pandas.core.frame.DataFrame

In [24]:
# Access to multiple columns

y = df[['Product','Category', 'Quantity']]
y

      Product     Category  Quantity
0      Laptop  Electronics         2
1  Smartphone  Electronics         3
2  Desk Chair    Furniture         5
3    Notebook   Stationery        10
4     Monitor  Electronics         1

In [25]:
# Access the value on the first row and the first column

df.iloc[0, 0]

1

In [26]:
# Access the value on the second row and the first column

df.iloc[1,0]

2

In [27]:
# Access the value on the first row and the third column

df.iloc[0,2]

'Electronics'

In [28]:
# Access the value on the second row and the third column
df.iloc[1,2]

'Electronics'

In [29]:
# Access the column using the name

df.loc[0, 'Product']

'Laptop'

In [30]:
# Access the column using the name

df.loc[1, 'CustomerCity']

'Los Angeles'

In [31]:
# Access the column using the name

df.loc[1, 'Total']

1800

In [32]:
# Slicing the dataframe

df.iloc[0:2, 0:3]

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics

In [33]:
# Slicing the dataframe

df.iloc[0:2, 1:3]

      Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics

In [34]:
# Slicing the dataframe using name

df.loc[0:2, 'OrderID':'Category']

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics
2        3  Desk Chair    Furniture