In [2]:
import pandas as pd
# Create a Series from a list
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:

print(s[1:4])   # Access a range of elements by label

1    20
2    30
3    40
dtype: int64

In [4]:
print(s.iloc[3]) # Access the element at position 3 (value 40)

40

In [5]:
print(s[2])     # Access the element with label 2 (value 30)

30

In [10]:
import pandas as pd
# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [11]:

print(df['Name'])  # Access the 'Name' column

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [13]:
print(df.iloc[2])   # Access the third row by position

Name        Charlie
Age              35
City    Los Angeles
Name: 2, dtype: object

In [14]:
print(df.loc[1])    # Access the second row by label

Name              Bob
Age                30
City    San Francisco
Name: 1, dtype: object

In [15]:
print(df[['Name', 'Age']])  # Select specific columns

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28

In [16]:
print(df[1:3])             # Select specific rows

      Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [18]:

unique_dates = df['Age'].unique()
print(unique_dates)

[25 30 35 28]

In [22]:
shape_dates = df.shape
print(shape_dates)

(4, 3)

In [23]:
high_above_102 = df[df['Age'] > 25]
print(high_above_102)

      Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [24]:

df.to_csv('trading_data.csv', index=False)

In [25]:
#write your code here
infoEstudents= {"Student":["David", "Samuel", "Terry", "Evan"],"Age":[27,24,22,32],"Country":["UK","Canada","China","USA"],"Course":["Python","Data Structures","Machine Learning","Web Development"],"Marks":[85,72,89,76]}
it=pd.DataFrame(infoEstudents)
it

  Student  Age Country            Course  Marks
0   David   27      UK            Python     85
1  Samuel   24  Canada   Data Structures     72
2   Terry   22   China  Machine Learning     89
3    Evan   32     USA   Web Development     76

In [26]:
b=it[["Marks"]]
b

   Marks
0     85
1     72
2     89
3     76

In [27]:
c=it[["Country","Course"]]
c

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [28]:
x = it['Student']
x

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: object

In [29]:
type(x)

pandas.core.series.Series

In [30]:
# Access the value on the first row and the first column

it.iloc[0, 0]

'David'

In [31]:
# Access the value on the first row and the third column

df.iloc[0,2]

'New York'

In [32]:
# Access the column using the name

it.loc[0, "Course"]

'Python'

Let us create a new dataframe. Now, let us set the "Student" column as an index column using the method set_index().

In [33]:
it2=it
it2=it2.set_index("Student")
it2

         Age Country            Course  Marks
Student
David     27      UK            Python     85
Samuel    24  Canada   Data Structures     72
Terry     22   China  Machine Learning     89
Evan      32     USA   Web Development     76

In [34]:
#To display the first 2 rows of new dataframe
it2.head(2)

         Age Country           Course  Marks
Student
David     27      UK           Python     85
Samuel    24  Canada  Data Structures     72

In [35]:
#Now, let us access the column using the name
it2.loc["Samuel", "Country"]

'Canada'

In [36]:
it2.loc["David","Age"]

27

In [37]:
it2.iloc[2,2]

'Machine Learning'

In [38]:
it.iloc[1:2, 1:4]

   Age Country           Course
1   24  Canada  Data Structures

let us do the slicing using loc() function on old dataframe it where index column is having labels as 0,1,2

In [39]:
it.loc[1:2,'Age':'Course']

   Age Country            Course
1   24  Canada   Data Structures
2   22   China  Machine Learning

In [40]:
#let us do the slicing using loc() function on new dataframe it2 where index column is Students having labels: Terry, Samuel, evan
it2.loc['Terry':'Evan', 'Age':'Marks']

         Age Country            Course  Marks
Student
Terry     22   China  Machine Learning     89
Evan      32     USA   Web Development     76

In [41]:
it.loc[2:3, 'Age':'Marks']

   Age Country            Course  Marks
2   22   China  Machine Learning     89
3   32     USA   Web Development     76